/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as GiftContractJson } from "../Gift.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace GiftTypes {
  export type Fields = {
    sender: Address;
    hashedSecret: HexString;
    announcementLockIntervall: bigint;
    version: bigint;
    isCancellable: boolean;
    announcedAddress: Address;
    announcementLockedUntil: bigint;
  };

  export type State = ContractState<Fields>;

  export type LockEvent = ContractEvent<{ by: Address; until: bigint }>;
  export type WithdrawEvent = ContractEvent<{ by: Address }>;
  export type CancelEvent = ContractEvent<{}>;

  export interface CallMethodTable {
    announce: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    withdraw: {
      params: CallContractParams<{ secret: HexString }>;
      result: CallContractResult<null>;
    };
    resetLock: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    cancel: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    getVersion: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    isCancellable: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<boolean>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    announce: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    withdraw: {
      params: SignExecuteContractMethodParams<{ secret: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    resetLock: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    cancel: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getVersion: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    isCancellable: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<GiftInstance, GiftTypes.Fields> {
  encodeFields(fields: GiftTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = { Lock: 0, Withdraw: 1, Cancel: 2 };
  consts = {
    ErrorCodes: {
      GiftLocked: BigInt("0"),
      UnannouncedCaller: BigInt("1"),
      WrongSecret: BigInt("2"),
      CallerIsNotSender: BigInt("3"),
      CancelIsNotAllowed: BigInt("4"),
    },
  };

  at(address: string): GiftInstance {
    return new GiftInstance(address);
  }

  tests = {
    announce: async (
      params: Omit<
        TestContractParamsWithoutMaps<GiftTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "announce", params, getContractByCodeHash);
    },
    withdraw: async (
      params: TestContractParamsWithoutMaps<
        GiftTypes.Fields,
        { secret: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdraw", params, getContractByCodeHash);
    },
    resetLock: async (
      params: Omit<
        TestContractParamsWithoutMaps<GiftTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "resetLock", params, getContractByCodeHash);
    },
    cancel: async (
      params: Omit<
        TestContractParamsWithoutMaps<GiftTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "cancel", params, getContractByCodeHash);
    },
    getVersion: async (
      params: Omit<
        TestContractParamsWithoutMaps<GiftTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getVersion", params, getContractByCodeHash);
    },
    isCancellable: async (
      params: Omit<
        TestContractParamsWithoutMaps<GiftTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(this, "isCancellable", params, getContractByCodeHash);
    },
  };

  stateForTest(initFields: GiftTypes.Fields, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Gift = new Factory(
  Contract.fromJson(
    GiftContractJson,
    "",
    "f717e29a3be9dc350eb757635317ceeb7cf0d935115866442e50cdb9d1eeaf33",
    []
  )
);

// Use this class to interact with the blockchain
export class GiftInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<GiftTypes.State> {
    return fetchContractState(Gift, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeLockEvent(
    options: EventSubscribeOptions<GiftTypes.LockEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Gift.contract,
      this,
      options,
      "Lock",
      fromCount
    );
  }

  subscribeWithdrawEvent(
    options: EventSubscribeOptions<GiftTypes.WithdrawEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Gift.contract,
      this,
      options,
      "Withdraw",
      fromCount
    );
  }

  subscribeCancelEvent(
    options: EventSubscribeOptions<GiftTypes.CancelEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Gift.contract,
      this,
      options,
      "Cancel",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      GiftTypes.LockEvent | GiftTypes.WithdrawEvent | GiftTypes.CancelEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(Gift.contract, this, options, fromCount);
  }

  view = {
    announce: async (
      params?: GiftTypes.CallMethodParams<"announce">
    ): Promise<GiftTypes.CallMethodResult<"announce">> => {
      return callMethod(
        Gift,
        this,
        "announce",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    withdraw: async (
      params: GiftTypes.CallMethodParams<"withdraw">
    ): Promise<GiftTypes.CallMethodResult<"withdraw">> => {
      return callMethod(Gift, this, "withdraw", params, getContractByCodeHash);
    },
    resetLock: async (
      params?: GiftTypes.CallMethodParams<"resetLock">
    ): Promise<GiftTypes.CallMethodResult<"resetLock">> => {
      return callMethod(
        Gift,
        this,
        "resetLock",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    cancel: async (
      params?: GiftTypes.CallMethodParams<"cancel">
    ): Promise<GiftTypes.CallMethodResult<"cancel">> => {
      return callMethod(
        Gift,
        this,
        "cancel",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getVersion: async (
      params?: GiftTypes.CallMethodParams<"getVersion">
    ): Promise<GiftTypes.CallMethodResult<"getVersion">> => {
      return callMethod(
        Gift,
        this,
        "getVersion",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    isCancellable: async (
      params?: GiftTypes.CallMethodParams<"isCancellable">
    ): Promise<GiftTypes.CallMethodResult<"isCancellable">> => {
      return callMethod(
        Gift,
        this,
        "isCancellable",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    announce: async (
      params: GiftTypes.SignExecuteMethodParams<"announce">
    ): Promise<GiftTypes.SignExecuteMethodResult<"announce">> => {
      return signExecuteMethod(Gift, this, "announce", params);
    },
    withdraw: async (
      params: GiftTypes.SignExecuteMethodParams<"withdraw">
    ): Promise<GiftTypes.SignExecuteMethodResult<"withdraw">> => {
      return signExecuteMethod(Gift, this, "withdraw", params);
    },
    resetLock: async (
      params: GiftTypes.SignExecuteMethodParams<"resetLock">
    ): Promise<GiftTypes.SignExecuteMethodResult<"resetLock">> => {
      return signExecuteMethod(Gift, this, "resetLock", params);
    },
    cancel: async (
      params: GiftTypes.SignExecuteMethodParams<"cancel">
    ): Promise<GiftTypes.SignExecuteMethodResult<"cancel">> => {
      return signExecuteMethod(Gift, this, "cancel", params);
    },
    getVersion: async (
      params: GiftTypes.SignExecuteMethodParams<"getVersion">
    ): Promise<GiftTypes.SignExecuteMethodResult<"getVersion">> => {
      return signExecuteMethod(Gift, this, "getVersion", params);
    },
    isCancellable: async (
      params: GiftTypes.SignExecuteMethodParams<"isCancellable">
    ): Promise<GiftTypes.SignExecuteMethodResult<"isCancellable">> => {
      return signExecuteMethod(Gift, this, "isCancellable", params);
    },
  };

  async multicall<Callss extends GiftTypes.MultiCallParams[]>(
    ...callss: Callss
  ): Promise<GiftTypes.MulticallReturnType<Callss>> {
    return (await multicallMethods(
      Gift,
      this,
      callss,
      getContractByCodeHash
    )) as GiftTypes.MulticallReturnType<Callss>;
  }
}
