name: GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    environment: ${{ vars.BUILD_CONTEXT_ENV }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
          cache: "yarn"

      - run: yarn install
      #- run: |
       #   echo 'module.exports.basePath = "/nextjs-template"' >> next.config.js
       
      - run: yarn run build
        env:
          UPLOAD_SENTRY_SOURCEMAPS: false
          CI: false
          NEXT_PUBLIC_URL: ${{ vars.PUBLIC_URL }}
          NEXT_PUBLIC_NETWORK: ${{ vars.NETWORK }}
          NEXT_PUBLIC_NODE_URL: ${{ vars.NODE_URL }}
          NEXT_PUBLIC_GIFT_FACTORY_ADDRESS: ${{ vars.GIFT_FACTORY_ADDRESS }}
        
      #- run: npm run export
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
